[2024-10-16T07:45:31.122+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_pageviews.analyze_data manual__2024-10-16T07:43:14+01:00 [queued]>
[2024-10-16T07:45:31.133+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_pageviews.analyze_data manual__2024-10-16T07:43:14+01:00 [queued]>
[2024-10-16T07:45:31.134+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-16T07:45:31.160+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): analyze_data> on 2024-10-16 06:43:14+00:00
[2024-10-16T07:45:31.167+0100] {standard_task_runner.py:60} INFO - Started process 28792 to run task
[2024-10-16T07:45:31.172+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia_pageviews', 'analyze_data', 'manual__2024-10-16T07:43:14+01:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/wiki/wiki.py', '--cfg-path', '/tmp/tmp_ijuwtlr']
[2024-10-16T07:45:31.175+0100] {standard_task_runner.py:88} INFO - Job 8: Subtask analyze_data
[2024-10-16T07:45:31.271+0100] {task_command.py:423} INFO - Running <TaskInstance: wikipedia_pageviews.analyze_data manual__2024-10-16T07:43:14+01:00 [running]> on host ZIZI.
[2024-10-16T07:45:31.383+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia_pageviews' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T06:43:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T07:43:14+01:00'
[2024-10-16T07:45:31.387+0100] {python.py:201} INFO - Done. Returned value was: <function get_top_company at 0x7f58f3a54040>
[2024-10-16T07:45:31.392+0100] {xcom.py:664} ERROR - Object of type function is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-10-16T07:45:31.395+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'function'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/zizi/airflow/airbox/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
[2024-10-16T07:45:31.408+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=wikipedia_pageviews, task_id=analyze_data, execution_date=20241016T064314, start_date=20241016T064531, end_date=20241016T064531
[2024-10-16T07:45:31.435+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task analyze_data (Object of type function is not JSON serializable; 28792)
[2024-10-16T07:45:31.466+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-16T07:45:31.499+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
